name = "EquationsOfState"
uuid = "0438fec6-b81c-52d9-9651-d286848f50a8"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "2.0.0"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[targets]
test = ["Test", "UnitfulAtomic"]
